# -*- coding: utf-8 -*-
"""coders ready-1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14q9buponGmEjCoBsW03MVVRzpKQTdb6S

Workshop Day 2
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import plotly.express as pr
import plotly.graph_objects as go

df = pd.read_csv('/content/drive/MyDrive/project_dataset.csv.xls')

df

df.head(12)

df.shape

df.dtypes

df.info

df.describe()

df.duplicated()

df.isna()

df.isna().sum()/df.shape[0]

df.dropna(axis=1, inplace=True)

df

data = df.sample(n=500, random_state=42)

data

data.count()

fig = go.Figure(data = go.Scatter(x=df['Distance'],y = df['DepTime'],mode='markers', marker=dict(color='red')))
fig.update_layout(title = 'Scatter Plot for Distance vs Departure time', xaxis_title = 'Distance Time',yaxis_title ='Departure Time')
fig.show()

line_data = df.groupby('Month')['ArrDelay'].mean().reset_index()
line_data

fig = go.Figure(data = go.Scatter(x=line_data['Month'],y = line_data['ArrDelay'],mode='lines', marker=dict(color='green')))
fig.update_layout(title = 'Monthly average delay plot for an year', xaxis_title = 'Months',yaxis_title ='Delay of flights (in minutes)')
fig.show()

fig = go.Figure(data = go.Scatter(x=line_data['Month'],y = line_data['ArrDelay'],mode='lines', marker=dict(color='green')))
fig.update_layout(title = 'Monthly average delay plot for an year', xaxis_title = 'Months',yaxis_title ='Delay of flights (in minutes)')
fig.show()

bar_data = df.groupby('DestState')['Flights'].sum().reset_index()
bar_data

fig = pr.bar(bar_data,x='DestState',y='Flights', title = 'Total number of flights from each destination states')
fig.show()

bub_data = df.groupby('Reporting_Airline')['Flights'].sum().reset_index()
bub_data

fig = pr.scatter(bub_data,x='Reporting_Airline',y='Flights', title = 'Total number of flights per reporting airlines',size = 'Flights',hover_name='Reporting_Airline',size_max=60)
fig.show()